#if !defined(AFX_IMAGE_H__F4D02647_6584_46CA_8F3B_9E2F1DE2D62C__INCLUDED_)
#define AFX_IMAGE_H__F4D02647_6584_46CA_8F3B_9E2F1DE2D62C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CImage wrapper class

class CImage : public COleDispatchDriver
{
public:
	CImage() {}		// Calls COleDispatchDriver default constructor
	CImage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CImage(const CImage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetIndex();
	void SetIndex(short nNewValue);
	CString GetKey();
	void SetKey(LPCTSTR lpszNewValue);
	VARIANT GetTag();
	void SetTag(const VARIANT& newValue);
	CPicture GetPicture();
	void SetRefPicture(LPDISPATCH newValue);
	void Draw(long hDC, VARIANT* x, VARIANT* y, VARIANT* Style);
	CPicture ExtractIcon();
	void SetRefTag(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMAGE_H__F4D02647_6584_46CA_8F3B_9E2F1DE2D62C__INCLUDED_)
