#if !defined(AFX_IMAGES_H__C6550A12_6277_4551_AB8B_284F8BB5C2B1__INCLUDED_)
#define AFX_IMAGES_H__C6550A12_6277_4551_AB8B_284F8BB5C2B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CImage;

/////////////////////////////////////////////////////////////////////////////
// CImages wrapper class

class CImages : public COleDispatchDriver
{
public:
	CImages() {}		// Calls COleDispatchDriver default constructor
	CImages(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CImages(const CImages& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetCount();
	void SetCount(short nNewValue);
	CImage Add(VARIANT* Index, VARIANT* Key, VARIANT* Picture);
	void Clear();
	CImage GetItem(VARIANT* Index);
	void SetRefItem(VARIANT* Index, LPDISPATCH newValue);
	void Remove(VARIANT* Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMAGES_H__C6550A12_6277_4551_AB8B_284F8BB5C2B1__INCLUDED_)
