#if !defined(AFX_IMAGELIST_H__2A462EAA_88AC_4502_8C9A_6506F9C46F3D__INCLUDED_)
#define AFX_IMAGELIST_H__2A462EAA_88AC_4502_8C9A_6506F9C46F3D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CImages;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CImageList1 wrapper class

class CImageList1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CImageList1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2c247f23, 0x8591, 0x11d1, { 0xb1, 0x6a, 0x0, 0xc0, 0xf0, 0x28, 0x36, 0x28 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	short GetImageHeight();
	void SetImageHeight(short nNewValue);
	short GetImageWidth();
	void SetImageWidth(short nNewValue);
	unsigned long GetMaskColor();
	void SetMaskColor(unsigned long newValue);
	BOOL GetUseMaskColor();
	void SetUseMaskColor(BOOL bNewValue);
	CImages GetListImages();
	void SetRefListImages(LPDISPATCH newValue);
	long GetHImageList();
	void SetHImageList(long nNewValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	CPicture Overlay(VARIANT* Key1, VARIANT* Key2);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMAGELIST_H__2A462EAA_88AC_4502_8C9A_6506F9C46F3D__INCLUDED_)
